### ISSUE TITLE
Different results with "/?search/" and "/search/"

### ISSUE THREAD

**Issue by armornetworkdev** [armornetworkdev/armor-explorer#14]
Why do I get different pages using these links that refer to the same block?

https://explorer.armornetwork.org/?search/45939a714318c488cf20b2b0556b84c0e0326ecbf32ad8bc004a78688002212b

https://explorer.armornetwork.org/search/45939a714318c488cf20b2b0556b84c0e0326ecbf32ad8bc004a78688002212b

**Comment by moshenskyDV** [comment]
@armornetworkdev I don't know where did you get first link, but it's wrong. There shouldn't be question character in the URL. First one works as expected: it shows main page.

**Comment by armornetworkdev** [comment]
If this link is not valid, it should tell me that the web does not exist, right? instead of sending me to the main web. Can we put a page for this type of links?

[This goes to the main webpage](https://explorer.armornetwork.org/?search/45939a714318c488cf20b2b0556b84c0e0326ecbf32ad8bc004a78688002212b)
[This goes to the main webpage](https://explorer.armornetwork.org/invented_url_armor)

I also don't understand why I get two different results in both links. Can we put a common web for these urls?

**Comment by moshenskyDV** [comment]
Everything after question sign - it's query string
`protocol://subdomain.domain.com/path/path/path?queryparam=queryvalue&queryparam2=queryvalue2`
So it's not really a part of a path to the target page, it's parameters.

PS: we should remove debug log on 404 page. To do this we should add environment variable `env=production`.

**Comment by armornetworkdev** [comment]
Ok, Understood. Yes I have to change env=production
