### ISSUE TITLE
Is package-lock.json file necessary?

### ISSUE THREAD

**Issue by armornetworkdev** [armornetworkdev/armor-explorer#3]
If I delete `package-lock.json` file and run `npm update` it works ok.

**Comment by moshenskyDV** [comment]
No, it should be presented in repository. Sorry, I forgot to mention that in production server we shouldn't use `npm install`, we should use `npm ci` instead. 
This command will install dependencies according to `package-lock.json` file. 

Why we need it: `package.json` doesn't contain actual versions of all installed modules, so `npm install` result can be different time by time (for example when some library updates). Using `package-lock.json` we guarantee that we install set of modules already tested on dev/local environment.

**Comment by armornetworkdev** [comment]
Ok, then I update README https://github.com/armornetworkdev/armor-explorer/pull/7
